language: python
python:
    - "3.8"
# installing dependencies
install:
    - pip install poetry
    - poetry install
# Running tests
script:
    - poetry run task coverage

after_success:
    - codecov
